Add TLS URL parameters
redis/go-redis pull request #2076
Opened 2022-04-23 13:50 UTC by benweissmann

Fixes https://github.com/go-redis/redis/issues/2024

2022-06-04 07:29 UTC, vmihailenco commented on options.go
> +		o.TLSConfig.InsecureSkipVerify = q.bool("TLSInsecureSkipVerify")
Are these options TLSMinVersion/TLSMaxVersion/TLSInsecureSkipVerify documented anywhere?

2023-09-10 01:25 UTC, gaby commented
@benweissmann @vmihailenco Any updates on this ?

2024-03-14 10:42 UTC, apurvasaraiya commented
@benweissmann @vmihailenco, any ETA for these changes to be released?

2025-07-21 06:47 UTC, vlasky commented
Is it really too much to ask to merge this PR? I think having TLS options is a no-brainer.

2025-08-05 12:25 UTC, ndyakov commented
@vlasky the option names in the PR are quite inconsistent with the rest of the option names which are `snake_case` and the ones in the pr are `CamelCase`. In the same time, the option `ServerName` is introduced without any meaningful prefix, which may lead users to think this is the actual `ServerName` that will be used for connecting to redis. Overall, this should be reworked. If you are up for it, please feel free to open a PR.

2025-08-05 12:25 UTC, ndyakov requested changes
The option names in the PR are quite inconsistent with the rest of the option names which are `snake_case` and the ones in the pr are `CamelCase`. In the same time, the option `ServerName` is introduced without any meaningful prefix, which may lead users to think this is the actual `ServerName` that will be used for connecting to redis. Overall, this should be reworked. @benweissmann let me know if you would like to continue working on this or we can close this PR

2025-08-14 07:56 UTC, ofekshenawa commented
Hi @benweissmann ,
I’ve opened a new PR based on your work in this one, since I didn’t have permissions to push changes to your fork.
The new PR includes your contributions along with some adjustments: https://github.com/redis/go-redis/pull/3475.

Thanks again for your work!

2025-09-02 13:07 UTC, ndyakov commented
Closing since the work on this will be continued in #3475 , thank you @benweissmann !

2025-09-02 13:07 UTC, closed without merging