fix: struct XInfoGroup add attributes EntriesRead and Lan to avoid de…
redis/go-redis pull request #2330
Opened 2022-12-22 19:31 UTC by lianghongle

…fault err

2022-12-22 19:41 UTC, lianghongle commented
127.0.0.1:6379> xinfo groups xxx
1)  1) "name"
    2) "153"
    3) "consumers"
    4) (integer) 1
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "1671679636702-0"
    9) "entries-read"
   10) (integer) 568896
   11) "lag"
   12) (integer) 2

2022-12-22 19:42 UTC, lianghongle commented
`127.0.0.1:6379> xinfo groups xx
1)  1) "name"
    2) "153"
    3) "consumers"
    4) (integer) 1
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "1671679636702-0"
    9) "entries-read"
   10) (integer) 568896
   11) "lag"
   12) (integer) 2`

2022-12-22 19:45 UTC, lianghongle commented
```
127.0.0.1:6379> xinfo groups xxx
1)  1) "name"
    2) "153"
    3) "consumers"
    4) (integer) 1
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "1671679636702-0"
    9) "entries-read"
   10) (integer) 568896
   11) "lag"
   12) (integer) 2
```

2022-12-23 08:02 UTC, monkey92t requested changes
The test should be added.

2023-03-21 20:29 UTC, clD11 commented
Is this still be worked on? Being able to retrieve the lag and entries read would be very useful. Thanks

2025-04-29 19:50 UTC, ndyakov commented
The `Lag` is present in current releases. Closing this one.

2025-04-29 19:50 UTC, closed without merging