newConn race fix
redis/go-redis pull request #2781
Opened 2023-11-01 13:15 UTC by nvorobev

2023-12-17 10:49 UTC, ofekshenawa commented
@nvorobev Could you please add unit tests for this issue?

2025-03-19 12:56 UTC, ndyakov commented
@nvorobev thank you for the contribution, please add tests so we can review the PR and proceed.

2025-03-19 12:58 UTC, ndyakov requested changes

2025-03-19 12:58 UTC, ndyakov commented on internal/pool/pool.go
> +
it should check if pool is closed before potential dialconn call.

2025-09-02 13:12 UTC, ndyakov commented
It has been couple of months, closing this as stale PR. @nvorobev feel free to open a new one based on the latest state of master.

2025-09-02 13:12 UTC, closed without merging