fix: race slice for list function of ring client
redis/go-redis pull request #2931
Opened 2024-03-01 03:27 UTC by rfyiamcool

### summary

`s1 := s0` is shallow copy. when concurrently process read and write (append) operator for slice, raise data race. so, use `copy()` to deep copy slice object.

![image](https://github.com/redis/go-redis/assets/3785409/262809ec-85ea-40d7-9e86-3ffc38958372)

### test

ut

```golang
func TestRaceSlice(t *testing.T) {
	var a1 = make([]string, 3)
	var b1 = []string{"a", "b", "c"}

	// race error
	a1 = b1

	// race ok
	// copy(a1, b1)

	fmt.Printf("a1 >%v", (*reflect.SliceHeader)(unsafe.Pointer(&a1)))
	fmt.Println()
	fmt.Printf("b1 >%v", (*reflect.SliceHeader)(unsafe.Pointer(&b1)))

	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < 10000; i++ {
			a1[0] = "aa"
		}
	}()

	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < 10000; i++ {
			b1[0] = "bb"
		}
	}()

	wg.Wait()
}

```

#### test result

```
=== RUN   TestRaceSlice
a1 >&{824636064176 3 3}
b1 >&{824636064176 3 3}==================
WARNING: DATA RACE
Write at 0x00c00023c1b0 by goroutine 8:
  github.com/redis/go-redis/v9_test.TestRaceSlice.func1()
      /Users/ruifengyun/github/rfyiamcool/go-redis/main_test.go:504 +0xcf

Previous write at 0x00c00023c1b0 by goroutine 9:
  github.com/redis/go-redis/v9_test.TestRaceSlice.func2()
      /Users/ruifengyun/github/rfyiamcool/go-redis/main_test.go:512 +0xcf

Goroutine 8 (running) created at:
  github.com/redis/go-redis/v9_test.TestRaceSlice()
      /Users/ruifengyun/github/rfyiamcool/go-redis/main_test.go:501 +0x427
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x44

Goroutine 9 (running) created at:
  github.com/redis/go-redis/v9_test.TestRaceSlice()
      /Users/ruifengyun/github/rfyiamcool/go-redis/main_test.go:509 +0x4e4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x44
==================
    testing.go:1465: race detected during execution of test
--- FAIL: TestRaceSlice (0.00s)
=== NAME  
    testing.go:1465: race detected during execution of test
FAIL
FAIL    github.com/redis/go-redis/v9    0.384s
FAIL
```

2025-02-07 09:23 UTC, ndyakov approved these changes

2025-02-11 05:26 UTC, monkey92t commented
@ndyakov  Please hold off on approving and merging; this PR has issues.

copy(c.shards.list, list) should be changed to copy(list, c.shards.list).

2025-02-11 09:44 UTC, ndyakov requested changes

2025-02-11 09:44 UTC, ndyakov commented on ring.go
> +		copy(c.shards.list, list)
```suggestion
		copy(list, c.shards.list)
```

2025-02-11 09:46 UTC, ndyakov commented
@monkey92t Thank you, I marked it based on the finding, but didn't do a proper review before approving. My bad.

2025-02-20 14:55 UTC, ndyakov approved these changes

2025-02-20 14:55 UTC, merged