Ensure that JSON.GET returns Nil response
redis/go-redis pull request #2987
Opened 2024-05-06 07:33 UTC by nic-gibson

Updated JSONCmd.readReply to return redis.Nil if no results.

2025-02-19 09:58 UTC, axilis-marko commented
I'm also having issues with this.

@nic-gibson do you know if this will be merged? Should we expect a non error when the key is missing for JSONGet?

2025-03-19 12:47 UTC, ndyakov commented
@nic-gibson can you enable contributions to your fork so we can resolve the conflicts and proceed with this PR.

2025-04-24 09:27 UTC, axilis-marko commented
Any updates here?

2025-04-24 10:01 UTC, ndyakov requested changes
Please update to latest master and fix the failing builds.

2025-08-11 15:44 UTC, ofekshenawa commented
Hi @nic-gibson,
I’ve opened a new PR based on your work in this one, since I didn’t have permissions to push changes to your fork.
The new PR includes your contributions along with some adjustments: [link](https://github.com/redis/go-redis/pull/3470).

Thanks again for your work!

2025-08-12 11:28 UTC, closed without merging