Return keys from commands
redis/go-redis pull request #3130
Opened 2024-09-20 15:45 UTC by ofekshenawa

2024-09-20 16:09 UTC, vladvildanov requested changes

2024-09-20 16:09 UTC, vladvildanov commented on command.go
> +	case "mget":
This approach isn't scalable, each time we need a new type of extracting we have to add a command here. `Cmder` is an interface that should be abstract as possible and should not contain any implementation specific (mget is an implementation specific in this case).

Cmder should return a keys, but shouldn't be aware about the keys position of specific command (this is implementation details), instead the specific command that implements this interface should define keys position for itself.

2024-09-23 07:11 UTC, vladvildanov requested changes

2024-09-23 07:11 UTC, vladvildanov commented on command.go
> +func (cmd *baseCmd) getInterleavedArguments() []string {
Nice! Make total sense

2024-09-23 07:11 UTC, vladvildanov commented on string_commands.go
> +	cmd.keys = append(cmd.keys, key)
Why do you need to append key here? You pass key as an argument in constructor `NewIntCmd(ctx, "append", key, value)`, so it's expected that by calling `cmd.Keys()` you'll get back your keys.

2025-04-22 05:36 UTC, ndyakov commented
@vladvildanov , @ofekshenawa should we close this one? Can someone explain what was the need and the plan for this change?

2025-04-23 20:56 UTC, ofekshenawa commented
This PR enables saving the keys used by commands—especially multi-key commands—for use in CSC.

2025-06-05 12:43 UTC, ndyakov commented
Hey @ofekshenawa are we planning to continue the work on this one? Should we revisit it after the request-response policy? I do think the command info that we have at hand may help.

2026-05-02 16:19 UTC, ofekshenawa commented
Implemented in CSC feature

2026-05-02 16:19 UTC, closed without merging