feat: add encoding.BinaryUnmarshaler in Scan
redis/go-redis pull request #3144
Opened 2024-10-03 11:26 UTC by zeze1004

issue: #3139 

Fixed issue where UUID fields could not be unmarshaled correctly.

2024-10-31 02:46 UTC, zeze1004 commented
Hi there, I was wondering if you could take a moment to review this PR when you have the time. Thanks! cc. @ofekshenawa, @monkey92t

2025-02-10 13:23 UTC, ndyakov commented
This one looks good to me. @zeze1004 do you think we can add full test with write and read from/to redis instance?

2025-02-20 14:20 UTC, ndyakov requested changes
@zeze1004 please add integration test to verify the data is correctly stored and retrieved from/to redis.

2025-03-09 13:49 UTC, zeze1004 commented
> @zeze1004 please add integration test to verify the data is correctly stored and retrieved from/to redis.

Sorry, I just checked, I'll add the test and mention it

2025-07-17 23:45 UTC, justinhwang commented on go.mod
> +	github.com/google/uuid v1.6.0
Should probably avoid adding a dependency just for tests, that would force people who import `go-redis` to import this as well

2025-07-28 11:36 UTC, closed without merging