added `Do` method for raw query by single conn from `pool.Conn()`
redis/go-redis pull request #3182
Opened 2024-11-04 15:08 UTC by Oleglacto

2024-11-04 15:11 UTC, Oleglacto commented
Hello! I want to call `Do` method when I got Conn from redis.Pool. This PR can help me do this

2024-12-04 12:10 UTC, Oleglacto commented
@vmihailenco can u make review please?

2025-02-20 16:31 UTC, ndyakov commented
@Oleglacto can you please describe your usecase and add tests?

2025-02-21 11:27 UTC, Oleglacto commented
@ndyakov It is necessary to execute a raw query on a connection from the pool. Currently, this capability is not available, and workarounds such as `Get`, `Set`, etc., have to be used.

2025-02-21 11:40 UTC, ndyakov commented
@Oleglacto on top of my head i cannot think why this should not be possible. Any ideas? How will this behave if you are working with a connection that is in a pub/sub state?

2025-02-21 12:01 UTC, ndyakov requested changes

2025-02-21 12:01 UTC, ndyakov commented on do_test.go
> +	})
test is failing

2025-02-28 11:49 UTC, Oleglacto commented
@ndyakov Thanks for waiting. Type Conn from [redis.go](https://github.com/redis/go-redis/blob/master/redis.go#L820) doesn't  support pub/sub. I added  this method for cmdble interface and it will works fine. 

I will trying to fix my test.

2025-03-04 11:34 UTC, ndyakov commented
@Oleglacto any specific reason why this is not in `commands.go` ? I don't see the need to add additional file for it.

2025-03-04 11:37 UTC, Oleglacto commented
I created a new file because I didn't know where to add the changes.

I'll move it now

2025-03-06 14:54 UTC, ndyakov approved these changes

2025-03-24 16:36 UTC, merged